"""Pydantic v2 DTO 强类型契约聚合包。

导出通用响应体、用户、角色、对话、Mod 及运营模块全部契约定义。

Usage:
    >>> from app.schemas import ApiResponse, UserLoginRequest, STV2Card
"""

from app.schemas.character import (
    CharacterAuthorDTO,
    CharacterCommentCreateRequest,
    CharacterCommentResponse,
    CharacterCreateRequest,
    CharacterDetailResponse,
    CharacterFilterParams,
    CharacterListItemResponse,
    CharacterMetricsDTO,
    CharacterUpdateRequest,
    RewardRequest,
    STV2Card,
    STV2Data,
    STV3Card,
    STV3Data,
    WorldBookEntryDTO,
)
from app.schemas.chat import (
    ChatMessageDTO,
    ChatSessionCreateRequest,
    ChatSessionResponse,
    ControlPanelDTO,
    NarrativeStateDTO,
    RollbackRequest,
    SendMessageRequest,
    SSEMetricsDTO,
    StoryBranchCreateRequest,
    StoryBranchDTO,
)
from app.schemas.common import (
    ApiErrorResponse,
    ApiResponse,
    PaginatedResponse,
    PaginationParams,
)
from app.schemas.mod import (
    ModCollectionCreateRequest,
    ModCollectionResponse,
    ModCreateRequest,
    ModItemResponse,
    ModPrioritySummaryResponse,
    ModPriorityUpdateRequest,
    ModSquareFilterParams,
    UserActiveModResponse,
    UserCustomItemCreateRequest,
    UserCustomItemResponse,
)
from app.schemas.ops import (
    ActivityResponse,
    NoticeResponse,
    SurveyResponse,
    SurveySubmitRequest,
)
from app.schemas.user import (
    BadgeDTO,
    DailyRewardResponse,
    InviteInfoResponse,
    TokenResponse,
    UserLoginRequest,
    UserProfileResponse,
    UserRegisterRequest,
    UserWalletResponse,
    WalletTransactionResponse,
)

__all__ = [
    "ActivityResponse",
    "ApiErrorResponse",
    "ApiResponse",
    "BadgeDTO",
    "CharacterAuthorDTO",
    "CharacterCommentCreateRequest",
    "CharacterCommentResponse",
    "CharacterCreateRequest",
    "CharacterDetailResponse",
    "CharacterFilterParams",
    "CharacterListItemResponse",
    "CharacterMetricsDTO",
    "CharacterUpdateRequest",
    "ChatMessageDTO",
    "ChatSessionCreateRequest",
    "ChatSessionResponse",
    "ControlPanelDTO",
    "DailyRewardResponse",
    "InviteInfoResponse",
    "ModCollectionCreateRequest",
    "ModCollectionResponse",
    "ModCreateRequest",
    "ModItemResponse",
    "ModPrioritySummaryResponse",
    "ModPriorityUpdateRequest",
    "ModSquareFilterParams",
    "NarrativeStateDTO",
    "NoticeResponse",
    "PaginatedResponse",
    "PaginationParams",
    "RewardRequest",
    "RollbackRequest",
    "SSEMetricsDTO",
    "STV2Card",
    "STV2Data",
    "STV3Card",
    "STV3Data",
    "SendMessageRequest",
    "StoryBranchCreateRequest",
    "StoryBranchDTO",
    "SurveyResponse",
    "SurveySubmitRequest",
    "TokenResponse",
    "UserActiveModResponse",
    "UserCustomItemCreateRequest",
    "UserCustomItemResponse",
    "UserLoginRequest",
    "UserProfileResponse",
    "UserRegisterRequest",
    "UserWalletResponse",
    "WalletTransactionResponse",
    "WorldBookEntryDTO",
]
