"""create_admin_rbac_tables

Revision ID: 482d96ccfe4e
Revises: 001_initial_schema
Create Date: 2026-09-03 20:43:02.147291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '482d96ccfe4e'
down_revision: Union[str, None] = '001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('operator_id', sa.UUID(), nullable=True),
    sa.Column('operator_name', sa.String(length=64), nullable=False),
    sa.Column('module', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('api_endpoint', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('request_params', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('cost_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_audit_logs_created_at'), 'admin_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_id'), 'admin_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_operator_id'), 'admin_audit_logs', ['operator_id'], unique=False)
    op.create_table('admin_departments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('leader', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['admin_departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_departments_id'), 'admin_departments', ['id'], unique=False)
    op.create_index(op.f('ix_admin_departments_parent_id'), 'admin_departments', ['parent_id'], unique=False)
    op.create_table('admin_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('component', sa.String(length=255), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['admin_permissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_permissions_code'), 'admin_permissions', ['code'], unique=True)
    op.create_index(op.f('ix_admin_permissions_id'), 'admin_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_admin_permissions_parent_id'), 'admin_permissions', ['parent_id'], unique=False)
    op.create_table('admin_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_roles_id'), 'admin_roles', ['id'], unique=False)
    op.create_index(op.f('ix_admin_roles_role_key'), 'admin_roles', ['role_key'], unique=True)
    op.create_table('admin_role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['admin_permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['admin_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('admin_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('real_name', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('avatar', sa.String(length=512), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('job_number', sa.String(length=32), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['admin_departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_department_id'), 'admin_users', ['department_id'], unique=False)
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.create_index(op.f('ix_admin_users_id'), 'admin_users', ['id'], unique=False)
    op.create_index(op.f('ix_admin_users_username'), 'admin_users', ['username'], unique=True)
    op.create_table('admin_user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['admin_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['admin_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_index(op.f('ix_character_comments_character_id'), 'character_comments', ['character_id'], unique=False)
    op.create_index(op.f('ix_character_comments_user_id'), 'character_comments', ['user_id'], unique=False)
    op.drop_index(op.f('idx_char_user_interact'), table_name='character_interactions')
    op.create_index('idx_character_user_interaction', 'character_interactions', ['character_id', 'user_id'], unique=True)
    op.drop_index(op.f('idx_worldbooks_char'), table_name='character_worldbooks')
    op.create_index(op.f('ix_character_worldbooks_character_id'), 'character_worldbooks', ['character_id'], unique=False)
    op.create_index(op.f('ix_characters_author_id'), 'characters', ['author_id'], unique=False)
    op.create_index(op.f('ix_characters_id'), 'characters', ['id'], unique=False)
    op.create_index(op.f('ix_characters_name'), 'characters', ['name'], unique=False)
    op.create_index(op.f('ix_chat_messages_branch_id'), 'chat_messages', ['branch_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.drop_index(op.f('idx_chat_sessions_user'), table_name='chat_sessions')
    op.create_index('idx_chat_sessions_user_updated', 'chat_sessions', ['user_id', 'updated_at'], unique=False)
    op.create_index(op.f('ix_chat_sessions_character_id'), 'chat_sessions', ['character_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_id'), 'chat_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_mod_collections_author_id'), 'mod_collections', ['author_id'], unique=False)
    op.create_index(op.f('ix_mods_author_id'), 'mods', ['author_id'], unique=False)
    op.create_index(op.f('ix_mods_id'), 'mods', ['id'], unique=False)
    op.create_index(op.f('ix_mods_title'), 'mods', ['title'], unique=False)
    op.create_index(op.f('ix_story_branches_session_id'), 'story_branches', ['session_id'], unique=False)
    op.create_index(op.f('ix_user_active_mods_user_id'), 'user_active_mods', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_custom_items_user_id'), 'user_custom_items', ['user_id'], unique=False)
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_invite_code'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_invite_code'), 'users', ['invite_code'], unique=True)
    op.create_index(op.f('ix_wallet_transactions_user_id'), 'wallet_transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_transactions_user_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_users_invite_code'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('idx_users_invite_code'), 'users', ['invite_code'], unique=True)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_user_custom_items_user_id'), table_name='user_custom_items')
    op.drop_index(op.f('ix_user_active_mods_user_id'), table_name='user_active_mods')
    op.drop_index(op.f('ix_story_branches_session_id'), table_name='story_branches')
    op.drop_index(op.f('ix_mods_title'), table_name='mods')
    op.drop_index(op.f('ix_mods_id'), table_name='mods')
    op.drop_index(op.f('ix_mods_author_id'), table_name='mods')
    op.drop_index(op.f('ix_mod_collections_author_id'), table_name='mod_collections')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_character_id'), table_name='chat_sessions')
    op.drop_index('idx_chat_sessions_user_updated', table_name='chat_sessions')
    op.create_index(op.f('idx_chat_sessions_user'), 'chat_sessions', ['user_id', 'updated_at'], unique=False)
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_branch_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_characters_name'), table_name='characters')
    op.drop_index(op.f('ix_characters_id'), table_name='characters')
    op.drop_index(op.f('ix_characters_author_id'), table_name='characters')
    op.drop_index(op.f('ix_character_worldbooks_character_id'), table_name='character_worldbooks')
    op.create_index(op.f('idx_worldbooks_char'), 'character_worldbooks', ['character_id'], unique=False)
    op.drop_index('idx_character_user_interaction', table_name='character_interactions')
    op.create_index(op.f('idx_char_user_interact'), 'character_interactions', ['character_id', 'user_id'], unique=True)
    op.drop_index(op.f('ix_character_comments_user_id'), table_name='character_comments')
    op.drop_index(op.f('ix_character_comments_character_id'), table_name='character_comments')
    op.drop_table('admin_user_roles')
    op.drop_index(op.f('ix_admin_users_username'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_id'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_department_id'), table_name='admin_users')
    op.drop_table('admin_users')
    op.drop_table('admin_role_permissions')
    op.drop_index(op.f('ix_admin_roles_role_key'), table_name='admin_roles')
    op.drop_index(op.f('ix_admin_roles_id'), table_name='admin_roles')
    op.drop_table('admin_roles')
    op.drop_index(op.f('ix_admin_permissions_parent_id'), table_name='admin_permissions')
    op.drop_index(op.f('ix_admin_permissions_id'), table_name='admin_permissions')
    op.drop_index(op.f('ix_admin_permissions_code'), table_name='admin_permissions')
    op.drop_table('admin_permissions')
    op.drop_index(op.f('ix_admin_departments_parent_id'), table_name='admin_departments')
    op.drop_index(op.f('ix_admin_departments_id'), table_name='admin_departments')
    op.drop_table('admin_departments')
    op.drop_index(op.f('ix_admin_audit_logs_operator_id'), table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_id'), table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_created_at'), table_name='admin_audit_logs')
    op.drop_table('admin_audit_logs')
    # ### end Alembic commands ###
